# Generated by Django 5.1.4 on 2026-09-22 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('body', models.TextField(verbose_name='回执正文')),
                ('checksum', models.CharField(max_length=16, verbose_name='校验短串')),
                ('issued_by', models.CharField(max_length=64, verbose_name='签发人')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签发时刻')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inspection.inspection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
